# Generated by Django 4.0 on 2021-12-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='image',
        ),
        migrations.CreateModel(
            name='EmployerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employer/activity/%Y/%m')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='careerapp.employer')),
            ],
        ),
    ]
