# Generated by Django 4.0 on 2021-12-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0003_remove_comment_post_comment_employer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='action',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='careerapp.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='careerapp.employer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('employer', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('employer', 'creator')},
        ),
        migrations.RemoveField(
            model_name='action',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
    ]
