# Generated by Django 4.0 on 2021-12-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0004_alter_action_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='careerapp.category'),
        ),
    ]
