# Generated by Django 4.0 on 2021-12-25 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0005_employer_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
