# Generated by Django 4.0 on 2021-12-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0006_alter_comment_options_post_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='candidates',
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.post')),
            ],
        ),
    ]
