# Generated by Django 4.0 on 2021-12-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0007_remove_post_candidates_recruitment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recruitment',
            unique_together={('post', 'candidate')},
        ),
    ]
