# Generated by Django 4.0 on 2021-12-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0008_alter_recruitment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='careerapp.user'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='careerapp.post'),
        ),
    ]
