# Generated by Django 4.0 on 2021-12-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0009_alter_recruitment_candidate_alter_recruitment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.user'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.post'),
        ),
    ]
