# Generated by Django 4.0 on 2021-12-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0010_alter_recruitment_candidate_alter_recruitment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
