# Generated by Django 4.0 on 2021-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0011_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateField(null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('cv', models.FileField(null=True, upload_to='uploads/CV/%Y/%m')),
                ('bang_cap', models.CharField(max_length=150, null=True)),
                ('skill', models.CharField(max_length=150, null=True)),
                ('experience', models.CharField(max_length=150, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
