# Generated by Django 4.0 on 2021-12-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0013_rename_bang_cap_candidate_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[(1, 'cadidate')], default=1, max_length=10),
        ),
    ]
