# Generated by Django 4.0 on 2021-12-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0014_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[(0, 'admin'), (1, 'candidate')], default=1, max_length=10),
        ),
    ]
