# Generated by Django 4.0.2 on 2022-05-29 08:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0017_alter_candidate_options_alter_employer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
