"""
Django settings for careerproject project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import mimetypes

mimetypes.add_type("text/css", ".css", True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f1h*q2fiqu4_==ju-=vpe)et-v=)alb@e%+s39rg=6-92#kx^8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'careerapp.apps.CareersConfig',
    'rest_framework',
    'oauth2_provider',
    'drf_yasg',
    'django_filters',
    'ckeditor',
    'cloudinary',
    'ckeditor_uploader',
    'django.contrib.sites',
    'cloudinary_storage',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        "rest_framework.authentication.SessionAuthentication",
    )
}

REST_USE_JWT = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
}

ACCOUNT_EMAIL_VERIFICATION = "none"

OAUTH2_INFO = {
    "client_id": "rDdzwd1YgvPtDxdxtfLgcAIC23RtQZCBRZNs8Nm9",
    "client_secret": "r47eNfJl0JMqwNYltUZWlsZLrzMl35JoinFonZ17AzpdysuCzzBohKBaeAV1XdNbDsjGsOBNSSlUXdBE8j0H3b3uUfUx6fQ5exw8WGytntZ9Iu97Cs6PoKbIGvYeXV1t"
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    "https://vongovantien.github.io",
    "https://frontend-careerapp.vercel.app"
]

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore'
}
INTERNAL_IPS = [
    '127.0.0.1'
]

ROOT_URLCONF = 'careerproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     # 'allauth.account.auth_backends.AuthenticationBackend',
#     # 'social_core.backends.google.GoogleOAuth2',
#     # 'rest_framework_social_oauth2.backends.DjangoOAuth2',
#
# ]

WSGI_APPLICATION = 'wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'careerdb3',
#         'USER': 'root',
#         'PASSWORD': '123456',
#         'HOST': '',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd51no5oofd4mdi',
        'USER': 'oblohmbmylfhac',
        'PASSWORD': 'a7761e642fe9a0ec34eb4f8ca6e3731cda5e210db0d652d5c5d5be6e351ca125',
        'HOST': 'ec2-3-227-154-49.compute-1.amazonaws.com',
        'POST': 5432
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'vtdb',
#         'USER': 'postgres',
#         'PASSWORD': 'meu@sds12@!#gh',
#         'HOST': '27.74.255.96',
#         'PORT': "5430"
#     }
# }

AUTH_USER_MODEL = 'careerapp.User'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'
# os.path.join(BASE_DIR, "media")
# MEDIA_ROOT = '%s/careerapp/media' % BASE_DIR
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
CKEDITOR_UPLOAD_PATH = '/post/'
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '468452925173-1gf7b50pir64v98vsi1npgkpjipbvfn4.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

TWILIO_ACCOUNT_SID = 'AC13b086f874a51edca6a6f038d152b4cf'
TWILIO_AUTH_TOKEN = '3c0c2e54e148847fded2884bbc4263fd'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dgct8zpvp',
    'API_KEY': '631943736442228',
    'API_SECRET': '4xKADk_UWqAKS7vlOl8qst_LUjw'
}
